version: "3.8"

services:
  proxy:
    image: nginx
    container_name: sziriusz-black
    stop_signal: SIGKILL
    ports:
      - "3333:3333"
    volumes:
      - ${PROJECT_HOME}:/usr/local/app/html:ro
      - ${PROJECT_HOME}/docker/conf/default/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PROJECT_HOME}/docker:/usr/local/app/docker:ro
    working_dir: /usr/local/app/html
    command: ["/usr/local/app/docker/scripts/start-proxy.sh"]
    logging:
      options:
        max-size: "10k"
        max-file: "3"

